### ISSUE TITLE
uTasker

### ISSUE THREAD

**Issue by huyrua291996** [uTasker/uTasker-Kinetis#2]
Does uTasker support the custom board. For example I use for my processor MKE02Z16VLC4
If yes, how do I do this
Thanks

**Comment by uTasker** [comment]
1. Choose the target that is closest to the custom board. Eg. FRDM_KE02Z40M may be in your case.
2. Search the project for this define to see the locations where it is customised.
3. Decide whether to add your own define or whether you prefer to use this define and adjust customisations where needed.
4. At each location where it is customised (eg. size of RAM, size of Flash, clock settings, GPIO uses) change the defines to suit your board or your requirements.
5. If you want to add your own board image and some switches/LEDs etc. for simulation you can see more or less how it is done from these videos:
https://youtu.be/vGk-b40EgL0
https://youtu.be/x0oe4kscIDI
Regards
Mark
