### ISSUE TITLE
External watchdog

### ISSUE THREAD

**Issue by huyrua291996** [uTasker/uTasker-Kinetis#4]
I write bootloader code
My board uses the external watchdog
And when the function 
void JumpToUserApplication(uint32_t userStartup)
{
    /* set up stack pointer */  
    __asm("ldr r1,[r0,#0]");
    __asm("mov sp,r1");
    /* jump to application reset vector */
    //asm("ADDS      r0,r0,#0x04 ");
    __asm("ldr r0,[r0,#4]");
    __asm("blx r0");
}
is running, the board always reset because the external watchdog
Can you give me some advise
Thanks

**Comment by uTasker** [comment]
Hi
This is not code from this project and it sounds as though your application is simply not running after it is jumped to.
Regards
Mark
