### ISSUE TITLE
code reading comments #1: assume "5" should be "6", to map to right UART Port ID.

### ISSUE THREAD

**Issue by navahooCite** [uTasker/uTasker-Kinetis#7]
https://github.com/uTasker/uTasker-Kinetis/blob/485886cf1d39c44d55510e292617270069e67c0f/WinSim/WinSimMain.cpp#L3499

fnProcessRx(ucRxBuffer, (unsigned short)iRxSize, 6);

same comments for following code block.

**Comment by uTasker** [comment]
Hi, Yes, the port number should be 6 and the following one should be 7.
I corrected and checked - I never simulated UARTs 6 and 7 (only available on some STM32) so didn't notice before...
