### ISSUE TITLE
code reading comments #2: dupicate type convert (unsigned char *)

### ISSUE THREAD

**Issue by navahooCite** [uTasker/uTasker-Kinetis#8]
https://github.com/uTasker/uTasker-Kinetis/blob/485886cf1d39c44d55510e292617270069e67c0f/Hardware/Kinetis/kinetis.c#L1020

Suppose should be:
  ptrVect = (VECTOR_TABLE *)((unsigned char *)&vector_ram);

**Comment by uTasker** [comment]
ptrVect = (VECTOR_TABLE *)&vector_ram; 

is also OK.
The unnecessary castings are not a problem but I'll change on next commit.

Regards

Mark
